version: "3"
services:
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: brewapps/node
    ports:
      - "5000:5000"
    volumes:
      - .:/home
    networks:
      - brewapps
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "brewapps"
    volumes:
      - ./mongodb:/data/db
    networks:
      - brewapps

networks:
  brewapps:
    driver: "bridge"

volumes:
  mongodb:
    driver: "local"
